In [70]:
import pandas as pd
goodreads = pd.read_csv('goodbooks.csv',error_bad_lines=False)
goodreads.head() #a csv from Goodreads but without genres and we will need genres...

b'Skipping line 3350: expected 12 fields, saw 13\nSkipping line 4704: expected 12 fields, saw 13\nSkipping line 5879: expected 12 fields, saw 13\nSkipping line 8981: expected 12 fields, saw 13\n'

,bookID,title,authors,average_rating,isbn,isbn13,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,1,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,9780439785969,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,2,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,9780439358071,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,4,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,9780439554893,eng,352,6333,244,11/1/2003,Scholastic
3,5,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,9780439655484,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,8,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,9780439682589,eng,2690,41428,164,9/13/2004,Scholastic

In [71]:
goodreads.shape #11123 rows and 12 columns

(11123, 12)

In [72]:
goodreads.dtypes

bookID                  int64
title                  object
authors                object
average_rating        float64
isbn                   object
isbn13                  int64
language_code          object
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date       object
publisher              object
dtype: object

In [73]:
goodreads.isnull().sum() #we have not null values

bookID                0
title                 0
authors               0
average_rating        0
isbn                  0
isbn13                0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publication_date      0
publisher             0
dtype: int64

In [74]:
goodreads = goodreads.drop(['bookID', 'isbn13'], axis=1) #let's drop this two columns because we won't need it

In [75]:
goodreads.head()

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher
0,Harry Potter and the Half-Blood Prince (Harry ...,J.K. Rowling/Mary GrandPré,4.57,0439785960,eng,652,2095690,27591,9/16/2006,Scholastic Inc.
1,Harry Potter and the Order of the Phoenix (Har...,J.K. Rowling/Mary GrandPré,4.49,0439358078,eng,870,2153167,29221,9/1/2004,Scholastic Inc.
2,Harry Potter and the Chamber of Secrets (Harry...,J.K. Rowling,4.42,0439554896,eng,352,6333,244,11/1/2003,Scholastic
3,Harry Potter and the Prisoner of Azkaban (Harr...,J.K. Rowling/Mary GrandPré,4.56,043965548X,eng,435,2339585,36325,5/1/2004,Scholastic Inc.
4,Harry Potter Boxed Set Books 1-5 (Harry Potte...,J.K. Rowling/Mary GrandPré,4.78,0439682584,eng,2690,41428,164,9/13/2004,Scholastic

In [76]:
books = pd.read_csv("booksummaries.txt",sep="\t",header=None) #a txt.file with genres and summaries of books. we will convert it into a csv. 't' means space and our txt has no headers

In [77]:
books = books.rename(columns={0:'bookid',1:'sdsdsd',2:"title",3:"authors",4:"date",5:"genre",6:"summary"}) #as we don't have a header, we will name each one of the columns in our table
books

,bookid,sdsdsd,title,authors,date,genre,summary
0,620,/m/0hhy,Animal Farm,George Orwell,1945-08-17,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,843,/m/0k36,A Clockwork Orange,Anthony Burgess,1962,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,986,/m/0ldx,The Plague,Albert Camus,1947,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,1756,/m/0sww,An Enquiry Concerning Human Understanding,David Hume,NaN,NaN,The argument of the Enquiry proceeds by a ser...
4,2080,/m/0wkt,A Fire Upon the Deep,Vernor Vinge,NaN,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...
...,...,...,...,...,...,...,...
16554,36934824,/m/0m0p0hr,Under Wildwood,Colin Meloy,2012-09-25,NaN,"Prue McKeel, having rescued her brother from ..."
16555,37054020,/m/04f1nbs,Transfer of Power,Vince Flynn,2000-06-01,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}",The reader first meets Rapp while he is doing...
16556,37122323,/m/0n5236t,Decoded,Jay-Z,2010-11-16,"{""/m/0xdf"": ""Autobiography""}",The book follows very rough chronological ord...
16557,37132319,/m/0n4bqb1,America Again: Re-becoming The Greatness We Ne...,Stephen Colbert,2012-10-02,NaN,Colbert addresses topics including Wall Stree...
16558,37159503,/m/073nkd,Poor Folk,Fyodor Dostoyevsky,1846,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ...",Makar Devushkin and Varvara Dobroselova are s...

In [78]:
books.shape #16559 rows and 7 columns

(16559, 7)

In [79]:
books.dtypes

bookid      int64
sdsdsd     object
title      object
authors    object
date       object
genre      object
summary    object
dtype: object

In [80]:
books.isnull().sum() #some null values in authors, date and genre

bookid        0
sdsdsd        0
title         0
authors    2382
date       5610
genre      3718
summary       0
dtype: int64

In [81]:
books = books.drop(['bookid', 'sdsdsd', 'date'], axis=1) #we drop this columns because we won't need it too...

In [82]:
books.head()

,title,authors,genre,summary
0,Animal Farm,George Orwell,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,Anthony Burgess,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,The Plague,Albert Camus,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,An Enquiry Concerning Human Understanding,David Hume,NaN,The argument of the Enquiry proceeds by a ser...
4,A Fire Upon the Deep,Vernor Vinge,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...

In [83]:
books

,title,authors,genre,summary
0,Animal Farm,George Orwell,"{""/m/016lj8"": ""Roman \u00e0 clef"", ""/m/06nbt"":...","Old Major, the old boar on the Manor Farm, ca..."
1,A Clockwork Orange,Anthony Burgess,"{""/m/06n90"": ""Science Fiction"", ""/m/0l67h"": ""N...","Alex, a teenager living in near-future Englan..."
2,The Plague,Albert Camus,"{""/m/02m4t"": ""Existentialism"", ""/m/02xlf"": ""Fi...",The text of The Plague is divided into five p...
3,An Enquiry Concerning Human Understanding,David Hume,NaN,The argument of the Enquiry proceeds by a ser...
4,A Fire Upon the Deep,Vernor Vinge,"{""/m/03lrw"": ""Hard science fiction"", ""/m/06n90...",The novel posits that space around the Milky ...
...,...,...,...,...
16554,Under Wildwood,Colin Meloy,NaN,"Prue McKeel, having rescued her brother from ..."
16555,Transfer of Power,Vince Flynn,"{""/m/01jfsb"": ""Thriller"", ""/m/02xlf"": ""Fiction""}",The reader first meets Rapp while he is doing...
16556,Decoded,Jay-Z,"{""/m/0xdf"": ""Autobiography""}",The book follows very rough chronological ord...
16557,America Again: Re-becoming The Greatness We Ne...,Stephen Colbert,NaN,Colbert addresses topics including Wall Stree...
16558,Poor Folk,Fyodor Dostoyevsky,"{""/m/02ql9"": ""Epistolary novel"", ""/m/014dfn"": ...",Makar Devushkin and Varvara Dobroselova are s...

In [99]:
goodreads.shape

(11123, 10)

In [100]:
goodreadsbooks = pd.merge(goodreads, books, on=["title", "authors"]) #merged inner
goodreadsbooks.head()

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publication_date,publisher,genre,summary
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,6/8/2004,iUniverse,"{""/m/014dfn"": ""Speculative fiction"", ""/m/03mfn...",The novel's plot follows the developing frien...
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,3/1/2002,Dramatists Play Service,NaN,The plot follows Heidi Holland from high scho...
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,9/15/2001,Kingfisher,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,6/1/2005,Simon & Schuster,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,10/1/1991,Ace,"{""/m/06n90"": ""Science Fiction"", ""/m/02xlf"": ""F...",The story focuses on a human raised on Mars a...

In [101]:
goodreadsbooks.shape #less data

(821, 12)

In [102]:
goodreadsbooks.isnull().sum() #less nan

title                  0
authors                0
average_rating         0
isbn                   0
language_code          0
  num_pages            0
ratings_count          0
text_reviews_count     0
publication_date       0
publisher              0
genre                 48
summary                0
dtype: int64

In [103]:
goodreadsbooks.dtypes

title                  object
authors                object
average_rating        float64
isbn                   object
language_code          object
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date       object
publisher              object
genre                  object
summary                object
dtype: object

In [104]:
goodreadsbooks['title'].apply(str)
goodreadsbooks.dtypes

title                  object
authors                object
average_rating        float64
isbn                   object
language_code          object
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publication_date       object
publisher              object
genre                  object
summary                object
dtype: object

In [105]:
goodreadsbooks['publication_date']= pd.to_datetime(goodreadsbooks['publication_date'])
goodreadsbooks.dtypes #convert 'publication_date' from object into datetime64

title                         object
authors                       object
average_rating               float64
isbn                          object
language_code                 object
  num_pages                    int64
ratings_count                  int64
text_reviews_count             int64
publication_date      datetime64[ns]
publisher                     object
genre                         object
summary                       object
dtype: object

In [106]:
from datetime import datetime as dt #convert 'publication_date' into 'three columns: 'day', 'month' and 'year'; it seems to be better for machine learning
goodreadsbooks['day']=goodreadsbooks['publication_date'].dt.day
goodreadsbooks['month']=goodreadsbooks['publication_date'].dt.month
goodreadsbooks['year']=goodreadsbooks['publication_date'].dt.year

In [107]:
goodreadsbooks.drop(['publication_date'],axis=1,inplace=True) #drop the column 'publication_date'

In [108]:
goodreadsbooks.dtypes #day, month and year as int64

title                  object
authors                object
average_rating        float64
isbn                   object
language_code          object
  num_pages             int64
ratings_count           int64
text_reviews_count      int64
publisher              object
genre                  object
summary                object
day                     int64
month                   int64
year                    int64
dtype: object

In [109]:
goodreadsbooks.head()

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,genre,summary,day,month,year
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,iUniverse,"{""/m/014dfn"": ""Speculative fiction"", ""/m/03mfn...",The novel's plot follows the developing frien...,8,6,2004
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,NaN,The plot follows Heidi Holland from high scho...,1,3,2002
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...,15,9,2001
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...,1,6,2005
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,"{""/m/06n90"": ""Science Fiction"", ""/m/02xlf"": ""F...",The story focuses on a human raised on Mars a...,1,10,1991

In [110]:
import re
dic1 = []
for i in range(len(goodreadsbooks.genre)):
    r1 = re.findall(r"[:\n\"](\w+\'?w* *-*\w*\'?w* *\w*\'?w*)[\"]",str(goodreadsbooks.genre[i]))
    #print(r1)
    for j in r1:
        if (j not in dic1):
            dic1.append(j)
print(dic1)

['Speculative fiction', 'Young adult literature', 'Business', "Children's literature", 'Adventure', 'Adventure novel', 'Fiction', 'Science Fiction', 'Novel', 'Postmodernism', 'Historical novel', 'Picaresque novel', 'Mystery', 'Crime Fiction', 'Non-fiction', 'Psychology', 'Dystopia', 'Novella', 'Thriller', 'Conspiracy fiction', 'Detective fiction', 'Suspense', 'Techno-thriller', 'Memoir', 'Travel', 'Biography', 'Travel literature', 'Autobiography', 'Satire', 'Romance novel', 'Alternate history', 'Epistolary novel', 'Fantasy', 'Non-fiction novel', 'Lost World', 'Philosophy', 'Inspirational', 'War novel', 'Horror', 'Historical fiction', 'Reference', 'Comic novel', 'Comedy', 'Anti-war', 'Absurdist fiction', 'Black comedy', 'Literary fiction', 'Picture book', 'Feminist science fiction', 'Bildungsroman', 'Ghost story', 'Morality play', 'Fairy tale', 'Industrial novel', 'Social science fiction', 'Spy fiction', 'Mathematics', 'Gothic fiction', 'Science', 'History', 'Fairytale fantasy', 'Autobiographical novel', 'Music', 'Soft science fiction', 'Psychological novel', 'Zombie', 'Nature', 'Magic realism', 'Vampire fiction', 'Catastrophic literature', 'Cyberpunk', 'Comedy of manners', 'Drama', 'Tragicomedy', 'Gay novel', 'Popular science', 'Social commentary', 'Short story', 'Social novel', 'Social criticism', 'Parallel novel', 'Western fiction', 'Western', 'Prose poetry', 'Poetry', 'Ergodic literature', 'Chivalric romance', 'Graphic novel', 'Sociology', 'Politics', 'Chick lit', 'Hardboiled', 'Comics', 'Humour', 'Cozy', 'Regency romance', 'Historical whodunnit', 'Invasion literature', 'Bangsian fantasy', 'Play', 'Religious text']

In [111]:
goodreadsbooks['genre'].fillna('{"no genre"}', inplace=True) #replace nan values in genre column with 'no genre'
goodreadsbooks.head()

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,genre,summary,day,month,year
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,iUniverse,"{""/m/014dfn"": ""Speculative fiction"", ""/m/03mfn...",The novel's plot follows the developing frien...,8,6,2004
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,"{""no genre""}",The plot follows Heidi Holland from high scho...,1,3,2002
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...,15,9,2001
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,"{""/m/09s1f"": ""Business"", ""/m/0dwly"": ""Children...",The novel is divided into 6 parts and 34 chap...,1,6,2005
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,"{""/m/06n90"": ""Science Fiction"", ""/m/02xlf"": ""F...",The story focuses on a human raised on Mars a...,1,10,1991

In [112]:
import re
for i in range(len(goodreadsbooks.genre)):
    r1 = re.findall(r"[:\n\"](\w+\'?w* *-*\w*\'?w* *\w*\'?w*)[\"]",str(goodreadsbooks.genre[i]))
    goodreadsbooks.loc[i, 'genre'] = str(r1)
    #(goodreadsbooks.genre[i])
    #print(goodreadsbooks.genre[i])
goodreadsbooks.head()
#clean the rows without trash

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,genre,summary,day,month,year
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,iUniverse,"['Speculative fiction', 'Young adult literature']",The novel's plot follows the developing frien...,8,6,2004
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,['no genre'],The plot follows Heidi Holland from high scho...,1,3,2002
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,"['Business', ""Children's literature"", 'Adventu...",The novel is divided into 6 parts and 34 chap...,15,9,2001
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,"['Business', ""Children's literature"", 'Adventu...",The novel is divided into 6 parts and 34 chap...,1,6,2005
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,"['Science Fiction', 'Fiction']",The story focuses on a human raised on Mars a...,1,10,1991

In [113]:
goodreadsbooks.isnull().sum() #without nans after replace 'nan' in column's 'genre' by 'no genre'

title                 0
authors               0
average_rating        0
isbn                  0
language_code         0
  num_pages           0
ratings_count         0
text_reviews_count    0
publisher             0
genre                 0
summary               0
day                   0
month                 0
year                  0
dtype: int64

In [114]:
type(goodreadsbooks.genre[0])

str

In [115]:
goodreadsbooks["genre"] = goodreadsbooks["genre"].apply(eval)

In [117]:
x = sum(goodreadsbooks.genre, [])
x #these are all the genres that we have

['Speculative fiction',
 'Young adult literature',
 'no genre',
 'Business',
 "Children's literature",
 'Adventure',
 'Adventure novel',
 'Speculative fiction',
 'Young adult literature',
 'Fiction',
 'Business',
 "Children's literature",
 'Adventure',
 'Adventure novel',
 'Speculative fiction',
 'Young adult literature',
 'Fiction',
 'Science Fiction',
 'Fiction',
 'Science Fiction',
 'Speculative fiction',
 'Science Fiction',
 'Speculative fiction',
 'Science Fiction',
 'Speculative fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Science Fiction',
 'Postmodernism',
 'Speculative fiction',
 'Historical novel',
 'Science Fiction',
 'Postmodernism',
 'Speculative fiction',
 'Historical novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'Speculative fiction',
 'Fiction',
 'Picaresque novel',
 'Mystery',
 'Fiction',
 'Novel',
 'Crime Fiction',
 'Fiction',
 'Non-fiction',
 'Speculative fiction',
 'Young adult literature',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Young adult literature',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Young adult literature',
 'Fiction',
 'Novel',
 'Fiction',
 'Psychology',
 'Science Fiction',
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'Psychology',
 'Science Fiction',
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Novella',
 'no genre',
 'Mystery',
 "Children's literature",
 'Young adult literature',
 'Fiction',
 'Novel',
 'Historical novel',
 'Historical novel',
 'Historical novel',
 'Historical novel',
 'Historical novel',
 'Thriller',
 'Conspiracy fiction',
 'Detective fiction',
 'Speculative fiction',
 'Mystery',
 'Crime Fiction',
 'Fiction',
 'Suspense',
 'Thriller',
 'Conspiracy fiction',
 'Detective fiction',
 'Speculative fiction',
 'Mystery',
 'Crime Fiction',
 'Fiction',
 'Suspense',
 'Thriller',
 'Techno-thriller',
 'Speculative fiction',
 'Science Fiction',
 'Thriller',
 'Techno-thriller',
 'Speculative fiction',
 'Science Fiction',
 'Thriller',
 'Techno-thriller',
 'Speculative fiction',
 'Science Fiction',
 'Non-fiction',
 'Fiction',
 'Novel',
 'Thriller',
 'Mystery',
 'Novel',
 'Fiction',
 'Suspense',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Memoir',
 'Fiction',
 'Historical novel',
 'Fiction',
 'Crime Fiction',
 'Mystery',
 'Fiction',
 'Suspense',
 'Travel',
 'Biography',
 'Travel literature',
 'Speculative fiction',
 'Non-fiction',
 'Autobiography',
 'Satire',
 'Fiction',
 'Romance novel',
 'Novel',
 'Satire',
 'Fiction',
 'Romance novel',
 'Novel',
 'Non-fiction',
 "Children's literature",
 'Fiction',
 "Children's literature",
 'Fiction',
 'Science Fiction',
 'Speculative fiction',
 'Fiction',
 'Science Fiction',
 'Speculative fiction',
 'Novel',
 'Speculative fiction',
 'Novel',
 'Fiction',
 'Non-fiction',
 'Non-fiction',
 'Non-fiction',
 'Thriller',
 'Mystery',
 'Novel',
 'Fiction',
 'Suspense',
 'Fiction',
 'Speculative fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Non-fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'Fiction',
 'Fiction',
 'Alternate history',
 'Science Fiction',
 'Speculative fiction',
 'Novel',
 'Epistolary novel',
 'Fiction',
 'Non-fiction',
 'Young adult literature',
 'Speculative fiction',
 "Children's literature",
 'Fiction',
 'Adventure novel',
 'Novel',
 "Children's literature",
 'Adventure novel',
 'Speculative fiction',
 'Fantasy',
 'Non-fiction novel',
 'Lost World',
 'Fiction',
 'Science Fiction',
 'Speculative fiction',
 "Children's literature",
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 "Children's literature",
 'Fiction',
 'Romance novel',
 'Novel',
 'Philosophy',
 'Novel',
 'Fiction',
 'Inspirational',
 'Philosophy',
 'Novel',
 'Fiction',
 'Inspirational',
 'Mystery',
 'War novel',
 'Fiction',
 'Mystery',
 'War novel',
 'Fiction',
 'Novel',
 'Romance novel',
 'Fiction',
 'Romance novel',
 'Fiction',
 'Romance novel',
 'Speculative fiction',
 'Fiction',
 'Romance novel',
 'Novel',
 'Fiction',
 'Novel',
 'Crime Fiction',
 'Mystery',
 'Fiction',
 'Novel',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Romance novel',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Thriller',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Autobiography',
 'Biography',
 'Novel',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Historical novel',
 'Novel',
 'Thriller',
 'Speculative fiction',
 'Horror',
 'Historical fiction',
 'Suspense',
 'Fiction',
 'Speculative fiction',
 'Historical fiction',
 'Fiction',
 'Satire',
 'Horror',
 'Speculative fiction',
 'Suspense',
 'Fiction',
 'Speculative fiction',
 'Horror',
 'Fiction',
 "Children's literature",
 'Young adult literature',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 "Children's literature",
 'Young adult literature',
 'Novel',
 'Science Fiction',
 "Children's literature",
 'Horror',
 'Novel',
 'Speculative fiction',
 'Fantasy',
 'Fiction',
 'Novel',
 'Novel',
 'Autobiography',
 'Biography',
 'Speculative fiction',
 'Memoir',
 'Fiction',
 'Autobiography',
 'Biography',
 'Speculative fiction',
 'Memoir',
 'Fiction',
 'Autobiography',
 'Biography',
 'Reference',
 'Memoir',
 'Novel',
 'Fiction',
 'Novel',
 'Thriller',
 'Mystery',
 'Fiction',
 'Historical novel',
 'Comic novel',
 'Novel',
 'Fiction',
 'Comedy',
 'Anti-war',
 'War novel',
 'Absurdist fiction',
 'Historical fiction',
 'Satire',
 'Black comedy',
 'Novel',
 'Fiction',
 'Literary fiction',
 'Novel',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'no genre',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novella',
 'Fiction',
 'Novella',
 'Fiction',
 'Novella',
 'Biography',
 'Memoir',
 "Children's literature",
 'Fiction',
 'Picture book',
 "Children's literature",
 'Fiction',
 'Novel',
 'Historical fiction',
 'Fiction',
 'Historical novel',
 'Historical fiction',
 'Fiction',
 'Historical novel',
 'Historical fiction',
 'Fiction',
 'Historical novel',
 'Fiction',
 'Science Fiction',
 'Feminist science fiction',
 'Speculative fiction',
 'Dystopia',
 'Novel',
 'Science Fiction',
 'Feminist science fiction',
 'Speculative fiction',
 'Dystopia',
 'Novel',
 'Science Fiction',
 "Children's literature",
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'Science Fiction',
 "Children's literature",
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'Autobiography',
 'Fiction',
 'Novel',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Historical novel',
 'Fiction',
 'Bildungsroman',
 'Novel',
 'Fiction',
 'Bildungsroman',
 'Novel',
 'Fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'no genre',
 'Ghost story',
 'Morality play',
 'Novella',
 'Speculative fiction',
 'Fairy tale',
 'Fiction',
 'Industrial novel',
 'Novel',
 'Non-fiction',
 'Mystery',
 'Novel',
 'Suspense',
 'Mystery',
 'Novel',
 'Fiction',
 'Suspense',
 'Mystery',
 "Children's literature",
 'Fiction',
 'Suspense',
 'Thriller',
 'Mystery',
 'Fiction',
 'Suspense',
 'Mystery',
 'Novel',
 'Fiction',
 'Suspense',
 'Thriller',
 'Fiction',
 'Suspense',
 'Mystery',
 'Novel',
 'Fiction',
 'Suspense',
 'Novel',
 'Fiction',
 'Comedy',
 'Thriller',
 'Fiction',
 'Thriller',
 'Fiction',
 'no genre',
 'Science Fiction',
 'Speculative fiction',
 'Fiction',
 'Social science fiction',
 'Non-fiction',
 'Science Fiction',
 'Novel',
 'Speculative fiction',
 'Mystery',
 'Satire',
 'Fiction',
 'Suspense',
 'no genre',
 'Spy fiction',
 'Thriller',
 'Fiction',
 'Romance novel',
 'Fiction',
 'Novel',
 'no genre',
 'Fiction',
 'Novel',
 "Children's literature",
 'Speculative fiction',
 'Romance novel',
 'Mystery',
 'Epistolary novel',
 'Fiction',
 'Mathematics',
 'Suspense',
 'Fiction',
 'Novel',
 'no genre',
 'Speculative fiction',
 'Fiction',
 'Speculative fiction',
 'Fiction',
 'Novel',
 "Children's literature",
 'Historical fiction',
 'Speculative fiction',
 'Fiction',
 'Gothic fiction',
 'Fiction',
 'Novel',
 'Historical fiction',
 'Fiction',
 'War novel',
 'Literary fiction',
 'Science Fiction',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Fantasy',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Novel',
 'no genre',
 'Fantasy',
 'Comedy',
 'Mathematics',
 'Science',
 'Historical fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fantasy',
 "Children's literature",
 'Adventure novel',
 'Memoir',
 'Science Fiction',
 "Children's literature",
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'Science Fiction',
 'Satire',
 'Techno-thriller',
 'Fiction',
 'Crime Fiction',
 'Mystery',
 'Science Fiction',
 'Fiction',
 'Suspense',
 'Science Fiction',
 "Children's literature",
 'Adventure novel',
 'Speculative fiction',
 'Fiction',
 'Lost World',
 'Suspense',
 'Speculative fiction',
 'Historical fiction',
 'Fantasy',
 'Fiction',
 'Historical novel',
 'Suspense',
 'Science Fiction',
 'Speculative fiction',
 'Fantasy',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Novel',
 "Children's literature",
 "Children's literature",
 'Fiction',
 'Speculative fiction',
 'Dystopia',
 'History',
 'Science Fiction',
 'Fantasy',
 'Fiction',
 'Fantasy',
 'Science Fiction',
 'Speculative fiction',
 'Horror',
 'Fiction',
 'Science Fiction',
 'Speculative fiction',
 'Fantasy',
 'Fiction',
 'Fantasy',
 'Fairytale fantasy',
 'Fantasy',
 'Speculative fiction',
 'Horror',
 'Fiction',
 'Fantasy',
 'Science Fiction',
 'Speculative fiction',
 'Young adult literature',
 'Mystery',
 'Fiction',
 'Suspense',
 'Historical novel',
 'no genre',
 'Novel',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Dystopia',
 'Science Fiction',
 'Novella',
 'Speculative fiction',
 'Satire',
 'Fiction',
 'Comic novel',
 'Speculative fiction',
 'Speculative fiction',
 'Historical novel',
 'Crime Fiction',
 'Mystery',
 'Fiction',
 'Suspense',
 'Speculative fiction',
 'Fiction',
 'Dystopia',
 'no genre',
 'no genre',
 'Science Fiction',
 'Speculative fiction',
 'Romance novel',
 'Mystery',
 'Fiction',
 'Dystopia',
 'Science Fiction',
 'Speculative fiction',
 'Romance novel',
 'Mystery',
 'Fiction',
 'Dystopia',
 'Science Fiction',
 'Speculative fiction',
 'Romance novel',
 'Mystery',
 'Fiction',
 'Dystopia',
 'Mystery',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Suspense',
 'Fiction',
 'Novel',
 'Fiction',
 'Speculative fiction',
 'Fiction',
 'Absurdist fiction',
 'Novel',
 'Science Fiction',
 'Novel',
 'Speculative fiction',
 'Fantasy',
 'Fiction',
 'Autobiographical novel',
 'Novel',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 'Non-fiction',
 'Non-fiction',
 'Non-fiction',
 'Fiction',
 'Novella',
 'Black comedy',
 'Satire',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Romance novel',
 'Fiction',
 'Novella',
 'Fiction',
 'Mystery',
 'Fiction',
 'Suspense',
 'Speculative fiction',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Novel',
 'Fantasy',
 'Speculative fiction',
 'Horror',
 'Crime Fiction',
 'Mystery',
 'Speculative fiction',
 'Fiction',
 'Suspense',
 'Speculative fiction',
 'Horror',
 'Fiction',
 'Suspense',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Suspense',
 'Fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 'Science Fiction',
 'Horror',
 'Speculative fiction',
 'Mystery',
 'Epistolary novel',
 'Fiction',
 'Suspense',
 'Science Fiction',
 'Horror',
 'Speculative fiction',
 'Mystery',
 'Epistolary novel',
 'Fiction',
 'Suspense',
 'War novel',
 'Romance novel',
 'Historical novel',
 'Historical novel',
 'Music',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Comedy',
 'Romance novel',
 'Fiction',
 'Comedy',
 'Romance novel',
 'Fiction',
 'Novel',
 'Novel',
 'Fiction',
 'no genre',
 'Fiction',
 'Crime Fiction',
 'Novel',
 'Novel',
 'Historical fiction',
 'Fiction',
 'Historical novel',
 'Historical fiction',
 'Fiction',
 'Historical novel',
 'Fiction',
 'Fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Science Fiction',
 'Speculative fiction',
 'no genre',
 'Fiction',
 "Children's literature",
 'Fiction',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 "Children's literature",
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Satire',
 'Fiction',
 'Novel',
 'Autobiography',
 'Biography',
 "Children's literature",
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fantasy',
 'Speculative fiction',
 'Horror',
 'Soft science fiction',
 'Epistolary novel',
 'Fiction',
 'no genre',
 'Fiction',
 'Novel',
 'Novel',
 "Children's literature",
 'Fiction',
 'Science Fiction',
 'Horror',
 'Novel',
 'Speculative fiction',
 'Dystopia',
 'Science Fiction',
 'Horror',
 'Novel',
 'Speculative fiction',
 'Dystopia',
 'Speculative fiction',
 'Horror',
 'War novel',
 'Mystery',
 'Speculative fiction',
 'Horror',
 'Non-fiction',
 'Fantasy',
 'Speculative fiction',
 'Horror',
 'Gothic fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 'Gothic fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 'Gothic fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 "Children's literature",
 'Horror',
 'Speculative fiction',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'War novel',
 'Fiction',
 'Psychological novel',
 'Fiction',
 'Novel',
 'Novel',
 'Postmodernism',
 'Speculative fiction',
 'Fiction',
 'Speculative fiction',
 'Fiction',
 'Novella',
 'Romance novel',
 'Romance novel',
 'Horror',
 'Speculative fiction',
 'Zombie',
 'Fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Novel',
 'Fantasy',
 'Novel',
 'Science Fiction',
 "Children's literature",
 'Fiction',
 'Psychological novel',
 'no genre',
 "Children's literature",
 'Reference',
 'Novel',
 'Romance novel',
 'Fiction',
 'Historical novel',
 "Children's literature",
 'Reference',
 'Novel',
 'Romance novel',
 'Fiction',
 'Historical novel',
 "Children's literature",
 'Reference',
 'Novel',
 'Romance novel',
 'Fiction',
 'Historical novel',
 "Children's literature",
 'Reference',
 'Novel',
 'Romance novel',
 'Fiction',
 'Historical novel',
 'Fiction',
 'Bildungsroman',
 'Fiction',
 'Fiction',
 'Novel',
 'Speculative fiction',
 'Fiction',
 'Novel',
 'Fiction',
 'Thriller',
 'Novel',
 'Nature',
 'Non-fiction',
 'Novel',
 'no genre',
 'no genre',
 'no genre',
 "Children's literature",
 'Fiction',
 'Historical novel',
 'Non-fiction',
 'Novel',
 ...]

In [118]:
from collections import Counter
c = Counter(x)
print(c) #count all the different genres

Counter({'Fiction': 490, 'Novel': 305, 'Speculative fiction': 269, "Children's literature": 112, 'Science Fiction': 110, 'Mystery': 89, 'Suspense': 78, 'Fantasy': 66, 'Romance novel': 57, 'Horror': 53, 'no genre': 48, 'Thriller': 43, 'Historical novel': 39, 'Crime Fiction': 35, 'Historical fiction': 32, 'Young adult literature': 29, 'Non-fiction': 24, 'Satire': 23, 'Dystopia': 22, 'Gothic fiction': 15, 'Autobiography': 14, 'Comedy': 13, 'Novella': 11, 'Biography': 11, 'Adventure novel': 10, 'War novel': 10, 'Memoir': 9, 'Bildungsroman': 9, 'Epistolary novel': 8, 'Black comedy': 7, 'Detective fiction': 6, 'Reference': 6, 'Spy fiction': 6, 'Techno-thriller': 5, 'Philosophy': 5, 'Literary fiction': 5, 'Picture book': 5, 'History': 5, 'Vampire fiction': 5, 'Alternate history': 4, 'Inspirational': 4, 'Science': 4, 'Autobiographical novel': 4, 'Psychological novel': 4, 'Parallel novel': 4, 'Humour': 4, 'Regency romance': 4, 'Postmodernism': 3, 'Mathematics': 3, 'Magic realism': 3, 'Western': 3, 'Sociology': 3, 'Business': 2, 'Adventure': 2, 'Picaresque novel': 2, 'Psychology': 2, 'Conspiracy fiction': 2, 'Travel': 2, 'Lost World': 2, 'Comic novel': 2, 'Absurdist fiction': 2, 'Feminist science fiction': 2, 'Ghost story': 2, 'Music': 2, 'Nature': 2, 'Drama': 2, 'Western fiction': 2, 'Chick lit': 2, 'Hardboiled': 2, 'Play': 2, 'Travel literature': 1, 'Non-fiction novel': 1, 'Anti-war': 1, 'Morality play': 1, 'Fairy tale': 1, 'Industrial novel': 1, 'Social science fiction': 1, 'Fairytale fantasy': 1, 'Soft science fiction': 1, 'Zombie': 1, 'Catastrophic literature': 1, 'Cyberpunk': 1, 'Comedy of manners': 1, 'Tragicomedy': 1, 'Gay novel': 1, 'Popular science': 1, 'Social commentary': 1, 'Short story': 1, 'Social novel': 1, 'Social criticism': 1, 'Prose poetry': 1, 'Poetry': 1, 'Ergodic literature': 1, 'Chivalric romance': 1, 'Graphic novel': 1, 'Politics': 1, 'Comics': 1, 'Cozy': 1, 'Historical whodunnit': 1, 'Invasion literature': 1, 'Bangsian fantasy': 1, 'Religious text': 1})

In [119]:
c.most_common(8) #the 8 genres more common

[('Fiction', 490),
 ('Novel', 305),
 ('Speculative fiction', 269),
 ("Children's literature", 112),
 ('Science Fiction', 110),
 ('Mystery', 89),
 ('Suspense', 78),
 ('Fantasy', 66)]

In [120]:
lis = []
for x in c.most_common(8):
    lis.append(x[0])
lis

['Fiction',
 'Novel',
 'Speculative fiction',
 "Children's literature",
 'Science Fiction',
 'Mystery',
 'Suspense',
 'Fantasy']

In [121]:
def search(row):
    genre_new= []
    for el in row:
        if el in lis:
            genre_new.append(el)
        else:
            genre_new.append('other')
    return list(set(genre_new)) #for the others genres that are not included in these 8 most common, we have 'other'

In [122]:
goodreadsbooks['genre'] = goodreadsbooks['genre'].apply(search)

In [123]:
goodreadsbooks.head()

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,genre,summary,day,month,year
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,iUniverse,"[other, Speculative fiction]",The novel's plot follows the developing frien...,8,6,2004
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,[other],The plot follows Heidi Holland from high scho...,1,3,2002
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,"[other, Fiction, Speculative fiction, Children...",The novel is divided into 6 parts and 34 chap...,15,9,2001
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,"[other, Fiction, Speculative fiction, Children...",The novel is divided into 6 parts and 34 chap...,1,6,2005
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,"[Science Fiction, Fiction]",The story focuses on a human raised on Mars a...,1,10,1991

In [124]:
goodreadsbooks['new_genre'] = goodreadsbooks['genre'].apply(lambda x : '|'.join(x))

In [125]:
goodreadsbooks

,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,genre,summary,day,month,year,new_genre
0,The Changeling,Zilpha Keatley Snyder,4.17,0595321801,eng,228,1176,96,iUniverse,"[other, Speculative fiction]",The novel's plot follows the developing frien...,8,6,2004,other|Speculative fiction
1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,[other],The plot follows Heidi Holland from high scho...,1,3,2002,other
2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,"[other, Fiction, Speculative fiction, Children...",The novel is divided into 6 parts and 34 chap...,15,9,2001,other|Fiction|Speculative fiction|Children's l...
3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,"[other, Fiction, Speculative fiction, Children...",The novel is divided into 6 parts and 34 chap...,1,6,2005,other|Fiction|Speculative fiction|Children's l...
4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,"[Science Fiction, Fiction]",The story focuses on a human raised on Mars a...,1,10,1991,Science Fiction|Fiction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
816,Arthur & George,Julian Barnes,3.70,1400097037,eng,445,11626,1141,Vintage International,"[other, Speculative fiction]","Set at the turn of the 20th century, the stor...",9,1,2007,other|Speculative fiction
817,Wartime Lies,Louis Begley,3.71,0449001172,eng,240,524,54,Ballantine Books,[other],Maciek and his aunt Tania are Polish Jews dur...,15,10,1997,other
818,Half Moon Investigations,Eoin Colfer,3.77,0786849606,en-US,304,279,41,Disney-Hyperion,"[Fiction, Mystery, Speculative fiction, Childr...",Fletcher Moon is a natural born investigator....,1,4,2007,Fiction|Mystery|Speculative fiction|Children's...
819,The Supernaturalist,Eoin Colfer,3.86,078685149X,en-US,267,24863,1001,Disney-Hyperion,"[other, Science Fiction, Speculative fiction]",The Supernaturalist takes place in Satellite ...,20,4,2005,other|Science Fiction|Speculative fiction
820,The Wish List,Eoin Colfer,3.77,0439443369,eng,252,13988,589,Scholastic Inc.,"[Fiction, Speculative fiction, Fantasy, Childr...",Meg Finn is in trouble. Her mother is dead an...,1,7,2004,Fiction|Speculative fiction|Fantasy|Children's...

In [202]:
#goodreadsbooks['fiction']=goodreadsbooks['new_genre'].apply(lambda x: x.contains('Fiction'))
goodreadsbooks['fiction']=goodreadsbooks['new_genre'].str.contains('Fiction').astype(int)
goodreadsbooks['novel']=goodreadsbooks['new_genre'].str.contains('Novel').astype(int)
goodreadsbooks['speculative_fiction']=goodreadsbooks['new_genre'].str.contains('Speculative fiction').astype(int)
goodreadsbooks['children_literature']=goodreadsbooks['new_genre'].str.contains('Children').astype(int)
goodreadsbooks['science_fiction']=goodreadsbooks['new_genre'].str.contains('Science Fiction').astype(int)
goodreadsbooks['mystery']=goodreadsbooks['new_genre'].str.contains('Mystery').astype(int)
goodreadsbooks['suspense']=goodreadsbooks['new_genre'].str.contains('Suspense').astype(int)
goodreadsbooks['fantasy']=goodreadsbooks['new_genre'].str.contains('Fantasy').astype(int)
#a kind of dummies; it creates a new column for each of one of 8 most relevant genres of books                                                                               
goodreadsbooks

,index,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,...,year,new_genre,fiction,novel,speculative_fiction,science_fiction,mystery,suspense,fantasy,children_literature
0,1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,...,2002,other,0,0,0,0,0,0,0,0
1,2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,...,2001,other|Fiction|Speculative fiction|Children's l...,1,0,1,0,0,0,0,1
2,3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,...,2005,other|Fiction|Speculative fiction|Children's l...,1,0,1,0,0,0,0,1
3,4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,...,1991,Science Fiction|Fiction,1,0,0,1,0,0,0,0
4,5,To Sail Beyond the Sunset,Robert A. Heinlein,3.87,0441748600,en-US,434,10293,193,Ace Books,...,1988,Science Fiction|Speculative fiction,1,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815,816,Arthur & George,Julian Barnes,3.70,1400097037,eng,445,11626,1141,Vintage International,...,2007,other|Speculative fiction,0,0,1,0,0,0,0,0
816,817,Wartime Lies,Louis Begley,3.71,0449001172,eng,240,524,54,Ballantine Books,...,1997,other,0,0,0,0,0,0,0,0
817,818,Half Moon Investigations,Eoin Colfer,3.77,0786849606,en-US,304,279,41,Disney-Hyperion,...,2007,Fiction|Mystery|Speculative fiction|Children's...,1,0,1,0,1,0,0,1
818,819,The Supernaturalist,Eoin Colfer,3.86,078685149X,en-US,267,24863,1001,Disney-Hyperion,...,2005,other|Science Fiction|Speculative fiction,1,0,1,1,0,0,0,0
819,820,The Wish List,Eoin Colfer,3.77,0439443369,eng,252,13988,589,Scholastic Inc.,...,2004,Fiction|Speculative fiction|Fantasy|Children's...,1,0,1,0,0,0,1,1

In [203]:
goodreadsbooks.dtypes

index                    int64
title                   object
authors                 object
average_rating         float64
isbn                    object
language_code           object
  num_pages              int64
ratings_count            int64
text_reviews_count       int64
publisher               object
genre                   object
summary                 object
day                      int64
month                    int64
year                     int64
new_genre               object
fiction                  int32
novel                    int32
speculative_fiction      int32
science_fiction          int32
mystery                  int32
suspense                 int32
fantasy                  int32
children_literature      int32
dtype: object

In [204]:
goodreadsbooks.drop(['new_genre'],axis=1,inplace=True)
goodreadsbooks.drop(['genre'],axis=1,inplace=True) #drop this columns because we won't need it anymore; we created 8 columns for the 8 most common genres of books that we have

In [205]:
goodreadsbooks.dtypes

index                    int64
title                   object
authors                 object
average_rating         float64
isbn                    object
language_code           object
  num_pages              int64
ratings_count            int64
text_reviews_count       int64
publisher               object
summary                 object
day                      int64
month                    int64
year                     int64
fiction                  int32
novel                    int32
speculative_fiction      int32
science_fiction          int32
mystery                  int32
suspense                 int32
fantasy                  int32
children_literature      int32
dtype: object

In [206]:
goodreadsbooks.to_csv('goodreadsbooks.csv') #creating a csv from the cleaned and final data

In [207]:
goodreadsbooks.head()

,index,title,authors,average_rating,isbn,language_code,num_pages,ratings_count,text_reviews_count,publisher,...,month,year,fiction,novel,speculative_fiction,science_fiction,mystery,suspense,fantasy,children_literature
0,1,The Heidi Chronicles,Wendy Wasserstein,3.75,0822205106,eng,81,1423,70,Dramatists Play Service,...,3,2002,0,0,0,0,0,0,0,0
1,2,Treasure Island,Robert Louis Stevenson,3.83,0753453800,eng,311,318753,6734,Kingfisher,...,9,2001,1,0,1,0,0,0,0,1
2,3,Treasure Island,Robert Louis Stevenson,3.83,1416500294,eng,245,5967,276,Simon & Schuster,...,6,2005,1,0,1,0,0,0,0,1
3,4,Stranger in a Strange Land,Robert A. Heinlein,3.92,0441788386,eng,528,251872,6241,Ace,...,10,1991,1,0,0,1,0,0,0,0
4,5,To Sail Beyond the Sunset,Robert A. Heinlein,3.87,0441748600,en-US,434,10293,193,Ace Books,...,6,1988,1,0,1,1,0,0,0,0